### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by PencilVoid** [IMB11/FogLooksGoodNow#15]
[crash-2023-03-18_14.32.17.1843-quilt_loader.txt](https://github.com/mineblock11/FogLooksGoodNow/files/11008886/crash-2023-03-18_14.32.17.1843-quilt_loader.txt)
Minecraft 1.19.3
Quilt Loader 0.18.2
FLGN 1.1.3 for Fabric 1.19.3

**Comment by IMB11** [comment]
My mods are not guarunteed to work with Quilt Loader.

This is due to compatability issues, and the fact the mod is not designed for the Quilt toolchain.

If you want to use my mod, I recommend either removing any mods that depend on the Quilt Standard Libraries (and remove QSL itself) or using Fabric Loader as recommended.
